docs/guides/apphub-guidelines.md

This PR adds the **security** content to the App Hub submission guidelines.

docs: add security section

---

docs/guides/spin-up-local-instance.md

edited the word "vesion" to "version" in the cli code

docs: edit word spelling

---

events/academy-workshops-2020.md
events/academy-workshops-2021.md
sidebarsEvents.js

This PR separates academies per year and adds links to workshops 2020

feat: separate academies

---

src/theme/BlogPostPage/index.js
src/theme/DocItem/index.js
src/theme/DocItem/styles.module.css

This PR adds utterances (GitHub App) to blog posts. Reference: [adding comment forum to docusaurus ](https://www.coderhackers.com/blog/2020/02/29/how-to-add-forum-to-docusaurus/)

feat: add utterances to blog posts

---

blog/2020-08-10-cross-origin-cookies.md
docs/guides/debug-instance.md

This PR updates the SameSite by Default Cookies workaround. 
References: 
* [SameSite Updates](https://www.chromium.org/updates/same-site)
* [Solution](https://www.reddit.com/r/chrome/comments/npaamb/i_can_no_longer_find_samesite_by_default_cookies/h0aeuva?utm_source=share&utm_medium=web2x&context=3) shared by Joakim 
Feel free to suggest changes! 👍

docs: update samesite-by-default-cookies

---

docs/conceptual/contribute-dev-portal.md
docs/conceptual/contribute.md
sidebars.js

This PR adds a contributions guide to the Developer Portal.

docs: add contributions-dev-portal

---

events/developer-meetups.md
sidebarsEvents.js

This PR adds a developer meetup page in the events section

docs: add meetup page

---

blog/2022-02-02-deep-dive-pwa.md
blog/authors.yml

Blog post as PWA deep dive meant for external use. Also added Kai and German as new blog authors

docs: pwa deep dive external blog post and new blog authors

---

docs/conceptual.md
docs/reference.md
sidebars.js

Make the sidebar a little better, and clarify some texts.
Before:
After:

Restructure sidebar for better navigation

---

docs/conceptual.md
docs/dev-videos.md
docs/reference.md
docs/tutorials.md

Thanks, @cooper-joe, for the suggestions

Better titles

---

blog/2019-12-12-ui-core-4.md
blog/2020-05-28-ui-5-release.md
blog/2022-02-10-automating-dhis2-integration-tests-in-junit-5.md
blog/2022-04-29-speeding-up-your-program-indicators-with-tracker-to-aggregate.md
blog/2022-07-27-app-platform-v10.md
docusaurus.config.js

- Added more blogs to the sidebar
- Added truncating to have a clearer overview
- Fixed some titles that now appeared in the sidebar
See the changes in the blog in this deployment: https://deploy-preview-97--dhis2-developer-portal.netlify.app/blog

Improve blog navigability

---

docs/quickstart.md

Updated version to latest and solved an issue where `--seed` was on a second line

Updated version & solved multiline

---

blog/2023-06-30-app-competition-results.md
blog/authors.yml

Blog in preview here: https://deploy-preview-123--dhis2-developer-portal.netlify.app/blog/2023/06/app-competition-results

feat: add app competition blog

---

docs/guides/publish-apphub.md

Workflow was a bit outdated, so I've updated it. Also added a `test`-step, since we should encourage that!

docs(publish-apphub): update workflow

---

community/stay-connected.md

Small update with more up-to-date information

docs: update page with proper info

---

docs-migrate.js
redirects.config.js

After merging several PR's, there's a few tiny changes needed to get everything to work.

chore: update source branches for external repositories

---

sidebars.js

added the plugin to the sidebar

docs: add plugin component to sidebar

---

sidebars.js

Accidentally had this link in the sidebar twice

docs: deduplicate reference

---

blog/2020-05-28-ui-5-release.md
blog/2021-11-03-app-platform-v8/index.md
docs-migrate.js
docs/guides/debug-instance.md
package.json
src/MeetupAttendees/BadgeList.js
src/MeetupAttendees/Badgepage.js
src/MeetupAttendees/UserBadge.js
src/nextSecondThursday.js
src/pages/index.js
src/theme/BlogPostPage/index.js
yarn.lock

Updated Docusaurus from 2.x to 3.x. Several changes were required mostly for stricter mdx validation

feat: upgrade docusaurus to last version

---

community/support.md
migrateDocsConfig.json

Depends on this to be merged: https://github.com/dhis2/ui/pull/1606
This updates the branch from a temporary one to master

chore: update  branch

---

.gitignore
migrateDocsConfig.json
sidebarsGuides.js

Added a new section inspired by the Capture plugins one:

docs: document how to implement Dashboard plugins (DHIS2-19492)
