dhis2/developer-portal

src/css/custom.css

The default footer link hover color is a bit too dark when used with the dark theme so I changed it to be the same as the non-hover color.

fix: use light footer link hover color with dark theme

---

docs/guides/apphub-guidelines.md

This PR adds the following content to the App Hub submission guidelines:
- the `ui` header bar must be included in all apps,
- the header bar is included automatically when using App Platform,
- the header bar must be manually included when not using App Platform.

feat: add headerbar section to app hub submission guidelines

---

docs/guides.md

How to spin up a DHIS2 local instance links to (https://developers.dhis2.org/docs/guides/guides/spin-up-local-instance) instead of (https://developers.dhis2.org/docs/guides/spin-up-local-instance) .

docs: Fixed URL

---

docs/guides/apphub-guidelines.md

This PR updates the App Hub Guidelines : _source code will be required_ (if I'm not mistaken, this [new PR](https://github.com/dhis2/app-hub/pull/458) is already making the **source code field** mandatory in the App Hub, as well as the **description** field). 
TODO:

docs: update guidelines

---

docs/guides/spin-up-local-instance.md

This PR intends add information on the `d2 cluster down --clean` command as suggested ([CLI-26](https://jira.dhis2.org/browse/CLI-26)). 
Please let me know if it makes sense 👍

chore: update d2 cluster guide

---

docs/guides/apphub-guidelines.md

This came up during a review of an app on the App Hub. Even though it is mentioned where the logo is download from the [https://github.com/dhis2/dhis2-identity#dont-add-other-shapes-to-the-logo](dhis2-identity-repo) it is under "best practices" and might be misunderstood/not taken seriously. I think it should be mentioned here as well.

docs(apphub): don't use DHIS2 logo in app icon

---

docusaurus.config.js

There's currently no way to get back to dhis2.org from developers.dhis2.org - this just adds a link to the footer, though we may want to add something more prominent in the header..?

docs: add link to dhis2.org main site

---

blog/2021-07-20-design-system-figma-library.md

This PR adds a blog post announcing the Design System Figma community library. The post contains a short overview of the library and some guidelines to get started. 
This PR is opened in draft as the final, released library link isn't available yet, but the rest of the content can be reviewed.
I also thought it might be useful to provide a link to the figma file somewhere permanent, rather than a time-based blog post. Thinking a kind of "Resources" section. I'm not sure which section fits this best, maybe _Reference_? What do you both think?

docs: design system figma library announcement

---

docs/guides/code-style.md

In version [8.0.0](https://github.com/dhis2/cli-style/blob/master/CHANGELOG.md#800-2021-05-05), d2-style's `check` and `apply` command verbs were moved to the top level.

fix: update d2-style commands format

---

docusaurus.config.js
src/css/custom.css

This PR adds a *domain navigation bar*, as used on other DHIS2 sites. This aligns the Developer Portal with other DHIS2 domains and provides quick navigation between domains.
This implementation uses the [Docusaurus `AnnouncementBar`](https://docusaurus.io/docs/api/themes/configuration#announcement-bar). This is a simple implementation that doesn't require custom theming, but it does rule out future use of the announcement bar for other purposes. **I think we should reach consensus that this is the right usage for the announcement bar for the foreseeable future.**

feat: domain navigation bar

---

docs/guides/spin-up-local-instance.md

* only put shell commands in a code block. This allows the reader to directly copy and paste the code from the documentation using its copy feature.
* fix broken `--seed` flag as one of the dashes in the flag was not actually a dash

fix: spin up local install shell commands

---

docs/guides/debug-instance.md

As discussed on Slack, here's a mention in our debug/troubleshooting instance guide of the network.cookie.sameSite.laxByDefault = false workaround to avoid CORS error messages when trying to connect DHIS2 applications on Firefox.

Added workaround for new CORS error on Firefox

---

docs/tutorials/dhis2-docker.md

Update the Docker Compose example with the correct DB dump variable ([`DHIS2_DB_DUMP_URL`](https://github.com/dhis2/dhis2-core/blob/master/docker-compose.yml#L50)) and remove the suggestion to only download the docker-compose file, as it doesn't really work.

docs: update Docker Compose example and wording

---

community/newsletter.mdx

Added a note to explain the reason for having multiple language options in the newsletter sign-up form. The current form doesn't explain that the language selection is not directly related to developer updates as the developer content is primiarly in English but the language options are for those interested in receiving general updates related to the languages of their selection.

chore: adding a note about language preferences

---

src/MeetupAttendees/BadgeList.js

The meetup page broke due to update in discourse, this fixes it. 
But due to `CORS` the API request is failing (it's working localhost) so in order to test it properly we'd need to add the Netlify.app domain to CORS in Discourse (I do not have permission)
https://meta.discourse.org/t/setup-cross-origin-resource-sharing-cors/270819

fix: show developer meetup page again

---

docusaurus.config.js

Small improvement to enable a new KapaAI feature for anonymous user tracking so we know how many unique people use Kapa.

chore: add flag to enable anonymous user tracking

---

sidebars.js

This adds [CustomDataProvider docs ](https://github.com/dhis2/app-runtime/blob/master/docs/advanced/CustomDataProvider.md) into the developer portal documentation. The CustomDataProvider is used for setting up tests, e.g. it's referenced in the sample test that new apps are initialized with (https://github.com/dhis2/app-platform/blob/master/cli/config/init.App.test.js#L9)

fix: add CustomDataProvider docs

---

blog/2019-12-12-ui-core-4.md
blog/2020-05-28-ui-5-release.md
blog/2022-07-27-app-platform-v10.md
blog/authors.yml

This will fix several pages where the author was not correctly visible, and also add titles to all authors indicating they're part of the core team

docs: update authors

---

docusaurus.config.js

JSON was missing from the language highlighter and is used in capture plugin docs.

chore:add json to languages for highlighting

---

sidebarsReferences.js

[LIBS-706](https://dhis2.atlassian.net/browse/LIBS-706)
[LIBS-706]: https://dhis2.atlassian.net/browse/LIBS-706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: add link to vite config extensions in sidebar
